import { Component, OnInit } from '@angular/core';
import { ModalController } from '@ionic/angular';

@Component({
  selector: 'app-activites',
  templateUrl: './activities.page.html',
  styleUrls: ['./activities.page.scss'],
})
export class ActivitiesPage implements OnInit {
  listActivites: any = [];
  value: any;

  constructor(private modalCtr: ModalController) { }

  ngOnInit() {
    let current = JSON.parse(localStorage.getItem('activite'));
    this.listActivites = [
      {
        id: 1, name: 'Athlétisme', nombres: 40, children: [
          { image: "assets/images/icon1.svg", checked: false, name: "Power lifting", width: "27px", height: "24px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon2.svg", checked: false, name: "Bench press", width: "27px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon3.svg", checked: false, name: "Abdominaux", width: "20px", height: "19px", padding: "12px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon4.svg", checked: false, name: "Cordes", width: "25px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon5.svg", checked: false, name: "Souplesse", width: "20px", height: "25px", padding: "9px 13px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon6.svg", checked: false, name: "Vélo elliptique", width: "21px", height: "26px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon7.svg", checked: false, name: "Tapis de course", width: "23px", height: "25px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]}]
      },

      {
        id: 2, name: 'Natation', nombres: 15, children: [
          { image: "assets/images/icon1.svg", checked: false, name: "Power lifting", width: "27px", height: "24px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon2.svg", checked: false, name: "Bench press", width: "27px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon3.svg", checked: false, name: "Abdominaux", width: "20px", height: "19px", padding: "12px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon4.svg", checked: false, name: "Cordes", width: "25px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon5.svg", checked: false, name: "Souplesse", width: "20px", height: "25px", padding: "9px 13px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon6.svg", checked: false, name: "Vélo elliptique", width: "21px", height: "26px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon7.svg", checked: false, name: "Tapis de course", width: "23px", height: "25px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]}]
      },

      {
        id: 3, name: "Handisport", nombres: 8, children: [
          { image: "assets/images/icon1.svg", checked: false, name: "Power lifting", width: "27px", height: "24px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon2.svg", checked: false, name: "Bench press", width: "27px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon3.svg", checked: false, name: "Abdominaux", width: "20px", height: "19px", padding: "12px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon4.svg", checked: false, name: "Cordes", width: "25px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon5.svg", checked: false, name: "Souplesse", width: "20px", height: "25px", padding: "9px 13px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon6.svg", checked: false, name: "Vélo elliptique", width: "21px", height: "26px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon7.svg", checked: false, name: "Tapis de course", width: "23px", height: "25px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]}]
      },
      {
        id: 4, name: "Football", nombres: 3, children: [
          { image: "assets/images/icon1.svg", checked: false, name: "Power lifting", width: "27px", height: "24px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon2.svg", checked: false, name: "Bench press", width: "27px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon3.svg", checked: false, name: "Abdominaux", width: "20px", height: "19px", padding: "12px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon4.svg", checked: false, name: "Cordes", width: "25px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon5.svg", checked: false, name: "Souplesse", width: "20px", height: "25px", padding: "9px 13px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon6.svg", checked: false, name: "Vélo elliptique", width: "21px", height: "26px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon7.svg", checked: false, name: "Tapis de course", width: "23px", height: "25px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]}]
      },
      {
        id: 5, name: "Basketball", nombres: "3", children: [
          { image: "assets/images/icon1.svg", checked: false, name: "Power lifting", width: "27px", height: "24px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon2.svg", checked: false, name: "Bench press", width: "27px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon3.svg", checked: false, name: "Abdominaux", width: "20px", height: "19px", padding: "12px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon4.svg", checked: false, name: "Cordes", width: "25px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon5.svg", checked: false, name: "Souplesse", width: "20px", height: "25px", padding: "9px 13px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon6.svg", checked: false, name: "Vélo elliptique", width: "21px", height: "26px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon7.svg", checked: false, name: "Tapis de course", width: "23px", height: "25px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]}]
      },
      {
        id: 6, name: "Musculation", nombres: 35, children: [
          { image: "assets/images/icon1.svg", checked: false, name: "Power lifting", width: "27px", height: "24px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon2.svg", checked: false, name: "Bench press", width: "27px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon3.svg", checked: false, name: "Abdominaux", width: "20px", height: "19px", padding: "12px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon4.svg", checked: false, name: "Cordes", width: "25px", height: "22px", padding: "11px 10px",width2:"37px", padding2: "34px 34px" ,details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon5.svg", checked: false, name: "Souplesse", width: "20px", height: "25px", padding: "9px 13px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon6.svg", checked: false, name: "Vélo elliptique", width: "21px", height: "26px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]},
          { image: "assets/images/icon7.svg", checked: false, name: "Tapis de course", width: "23px", height: "25px", padding: "9px 14px" ,width2:"37px", padding2: "34px 34px",details:[{name:'Corps haut',value:'20',image:'assets/images/corps-haut.svg'},{name:'Corps bas',value:'100',image:'assets/images/corps-bas.svg'},{name:'Cardio',value:'20',image:'assets/images/cardio.svg'},{name:'Explosivité',value:'20',image:'assets/images/explosivite.svg'},{name:'Souplesse',value:'20',image:'assets/images/souplesse.svg'},{name:'Gainage',value:'20',image:'assets/images/gainage.svg'}]}]
      }];
    if (current) {
      for (let item of this.listActivites) {
        for (let activite of item.children) {
          if (activite.name == current.name) {
            activite.checked = true;
          }
        }
      }
    }
  }

  iconWork(id: string) {
    let icon1 = document.getElementById(id);
    icon1.style.display = "none";

    let icon2 = document.getElementById(id + 'icon2');
    icon2.style.display = "block";
    this.value = id + 'icon2';

  }

  revIconWork(id: string) {
    let icon1 = document.getElementById(id);
    icon1.style.display = "block";

    let icon2 = document.getElementById(id + 'icon2');
    icon2.style.display = "none";
    this.value = id;

  }

  async close() {
    const closeModal: string = 'Modal Closed';
    await this.modalCtr.dismiss(closeModal);
  }

  checkActivite(item) {
    item.checked =true;
    localStorage.setItem('activite', JSON.stringify(item));
    this.modalCtr.dismiss();
  }
}
